import {
  Bot,
  CalendarClock,
  ChartNoAxesColumn,
  FileCheck2,
  GitBranch,
  History,
  Layers3,
  ListTodo,
  Network,
  Plug,
  Settings2,
  Share2,
} from 'lucide-react';
export const WORKSPACE_VIEWS = [
  {
    id: 'kanban',
    label: 'Tasks',
    description: 'Plan, execute and review work.',
    icon: Layers3,
    group: 'tasks',
    primary: true,
  },
  {
    id: 'topology',
    label: 'Projects',
    description: 'Explore codebase dependencies and project worktrees.',
    icon: Network,
    group: 'project',
    primary: true,
  },
  {
    id: 'agents',
    label: 'Agents',
    description: 'Manage runners, accounts and configuration.',
    icon: Bot,
    group: 'agents',
    primary: false,
  },
  {
    id: 'mcps',
    label: 'Connections',
    description: 'Install and configure MCP tools.',
    icon: Plug,
    group: 'connections',
    primary: false,
  },
  {
    id: 'usage',
    label: 'Usage',
    description: 'Understand consumption and account capacity.',
    icon: ChartNoAxesColumn,
    group: 'usage',
    primary: true,
  },
  {
    id: 'repo-todos',
    label: 'Repo TODOs',
    description: 'Tasks: view, edit and create repository TODOs and roadmaps.',
    icon: ListTodo,
    group: 'tasks',
    primary: false,
  },
  {
    id: 'browser',
    label: 'Evidence',
    description: 'Tasks: screenshots and check results.',
    icon: FileCheck2,
    group: 'tasks',
    primary: false,
  },
  {
    id: 'schedules',
    label: 'Recurring',
    description: 'Tasks: schedules and automatic runs.',
    icon: CalendarClock,
    group: 'tasks',
    primary: false,
  },
  {
    id: 'worktrees',
    label: 'Worktrees',
    description: 'Project: inspect and clean up branches.',
    icon: GitBranch,
    group: 'project',
    primary: false,
  },
  {
    id: 'project-settings',
    label: 'Project context',
    description: 'Repository preferences, instructions and verification.',
    icon: Settings2,
    group: 'project',
    primary: false,
  },
  {
    id: 'agent-settings',
    label: 'Agent configuration',
    description: 'Agents: accounts, models, paths and defaults.',
    icon: Settings2,
    group: 'agents',
    primary: false,
  },
  {
    id: 'audit',
    label: 'Diagnostics',
    description: 'Settings: activity log, routing and discovery events.',
    icon: History,
    group: 'settings',
    primary: false,
  },
  {
    id: 'mesh',
    label: 'System',
    description: 'Settings: this computer and device information.',
    icon: Share2,
    group: 'settings',
    primary: false,
  },
] as const;
export type ActiveTab = (typeof WORKSPACE_VIEWS)[number]['id'];
export function navigateWorkspace(tab: ActiveTab) {
  window.dispatchEvent(new CustomEvent('jackalope:navigate', { detail: tab }));
}
