import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pnpm = process.env.npm_execpath;
if (!pnpm || !/\.[cm]?js$/i.test(pnpm)) throw new Error('Run with pnpm licenses:generate.');
const execute = (command, args) =>
  JSON.parse(
    execFileSync(command, args, {
      cwd: root,
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
      windowsHide: true,
    }),
  );
const npm = execute(process.execPath, [pnpm, 'licenses', 'list', '--json']);
const cargo = execute('cargo', [
  'metadata',
  '--locked',
  '--manifest-path',
  'apps/desktop/src-tauri/Cargo.toml',
  '--format-version',
  '1',
]);
const escapeCell = (value) =>
  String(value ?? 'Unspecified')
    .replaceAll('|', '\\|')
    .replaceAll('\n', ' ');
const jsRows = Object.values(npm)
  .flat()
  .map((item) => [item.name, item.versions.join(', '), item.license]);
const rustRows = cargo.packages
  .filter((item) => item.source)
  .map((item) => [item.name, item.version, item.license]);
const table = (rows) =>
  `| Package | Version | Declared license |\n| --- | --- | --- |\n${rows
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map((row) => `| ${row.map(escapeCell).join(' | ')} |`)
    .join('\n')}`;
const report = `# Dependency license inventory

Generated by \`pnpm licenses:generate\` from installed JavaScript packages and the locked
Cargo dependency graph. Includes development dependencies; optional JavaScript
packages reflect the installation platform. Review this inventory when changing
dependencies and retain the upstream license/notice files when distributing them.
The table records package metadata, not a legal review of every source file.

The application code uses [Apache-2.0](../LICENSE). Shared vector branding is in
\`packages/brand\`. Plus Jakarta Sans and JetBrains Mono are bundled under OFL-1.1;
their full license texts are included in both apps' \`public/licenses\` directories.
Website screenshots and walkthroughs use explicit fictional sample data.
Task interaction patterns reference Beautiful UI; see [DESIGN.md](DESIGN.md).
The desktop bundles agent-browser's native executable, Apache-2.0 license and
embedded axe-core notices; see [BROWSER-AUTOMATION.md](BROWSER-AUTOMATION.md).

## JavaScript packages

${table(jsRows)}

## Rust packages

${table(rustRows)}
`;
writeFileSync(new URL('../docs/DEPENDENCIES.md', import.meta.url), report);
const production = execute(process.execPath, [pnpm, 'licenses', 'list', '--prod', '--json']);
const packages = [
  ...Object.values(production)
    .flat()
    .flatMap((item) =>
      item.paths.map((directory) => ({
        directory,
        name: `${item.name} ${item.versions.join(', ')}`,
      })),
    ),
  ...cargo.packages
    .filter((item) => item.source)
    .map((item) => ({
      directory: path.dirname(item.manifest_path),
      name: `${item.name} ${item.version}`,
    })),
];
const notices = new Map();
for (const item of packages) {
  for (const entry of readdirSync(item.directory, { withFileTypes: true })) {
    if (!entry.isFile() || !/^(?:licen[sc]e|copying|notice|unlicense)(?:[.-]|$)/i.test(entry.name))
      continue;
    const text = readFileSync(path.join(item.directory, entry.name), 'utf8').trim();
    if (!text) continue;
    const owners = notices.get(text) ?? new Set();
    owners.add(`${item.name} (${entry.name})`);
    notices.set(text, owners);
  }
}
const sections = [...notices].map(
  ([text, owners]) => `${[...owners].sort().join('\n')}\n\n${text}`,
);
sections.sort();
writeFileSync(
  new URL('../apps/desktop/public/licenses/dependencies.txt', import.meta.url),
  `Dependency license and notice files\n\nGenerated from installed production JavaScript packages and the locked Rust dependency graph.\nIncludes optional target dependencies. Identical texts are grouped; package declarations are listed in docs/DEPENDENCIES.md.\n\n${sections.join('\n\n============================================================\n\n')}\n`,
);
console.log(`Recorded ${jsRows.length} JavaScript and ${rustRows.length} Rust packages.`);
