import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const pnpm = process.env.npm_execpath;
if (!pnpm || !/\.[cm]?js$/i.test(pnpm)) throw new Error('Run with pnpm licenses:generate.');
const execute = (command, args) =>
  JSON.parse(
    execFileSync(command, args, {
      cwd: root,
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
      windowsHide: true,
    }),
  );
const npm = execute(process.execPath, [pnpm, 'licenses', 'list', '--json']);
const cargo = execute('cargo', [
  'metadata',
  '--locked',
  '--manifest-path',
  'apps/desktop/src-tauri/Cargo.toml',
  '--format-version',
  '1',
]);
const escapeCell = (value) =>
  String(value ?? 'Unspecified')
    .replaceAll('|', '\\|')
    .replaceAll('\n', ' ');
const jsRows = Object.values(npm)
  .flat()
  .map((item) => [item.name, item.versions.join(', '), item.license]);
const rustRows = cargo.packages
  .filter((item) => item.source)
  .map((item) => [item.name, item.version, item.license]);
const table = (rows) =>
  `| Package | Version | Declared license |\n| --- | --- | --- |\n${rows
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map((row) => `| ${row.map(escapeCell).join(' | ')} |`)
    .join('\n')}`;
const report = `# Dependency license inventory

Generated by \`pnpm licenses:generate\` from installed JavaScript packages and the locked
Cargo dependency graph. Includes development dependencies; optional JavaScript
packages reflect the installation platform. Review this inventory when changing
dependencies and retain the upstream license/notice files when distributing them.
The table records package metadata, not a legal review of every source file.

The application code uses [Apache-2.0](../LICENSE). Shared vector branding is in
\`packages/brand\`. Plus Jakarta Sans and JetBrains Mono are bundled under OFL-1.1;
their full license texts are included in both apps' \`public/licenses\` directories.
Website screenshots and walkthroughs use explicit fictional sample data.
Task interaction patterns reference Beautiful UI; see [DESIGN.md](DESIGN.md).

## JavaScript packages

${table(jsRows)}

## Rust packages

${table(rustRows)}
`;
writeFileSync(new URL('../docs/DEPENDENCIES.md', import.meta.url), report);
console.log(`Recorded ${jsRows.length} JavaScript and ${rustRows.length} Rust packages.`);
