!define JACKALOPE_SURFACE "f7f7f8"
!define JACKALOPE_TEXT "232225"
!macro JACKALOPE_ARTWORK_SCALES UN
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 120
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 144
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 168
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 192
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 216
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 240
  !insertmacro JACKALOPE_ARTWORK_SCALE "${UN}" 288
!macroend
